# Generated by Django 5.2.7 on 2025-11-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('PENDIDIKAN', 'Pendidikan'), ('PEKERJAAN', 'Pekerjaan'), ('USIA', 'Kelompok Usia'), ('AGAMA', 'Agama')], db_index=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Data Statistik',
                'verbose_name_plural': 'Data Statistik',
                'unique_together': {('kategori', 'label')},
            },
        ),
    ]
