# Generated by Django 5.2.7 on 2025-11-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0003_pindah_data_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastatistik',
            options={'verbose_name': 'Data Statistik', 'verbose_name_plural': 'Data Statistik'},
        ),
        migrations.AlterUniqueTogether(
            name='datastatistik',
            unique_together={('kategori', 'label')},
        ),
        migrations.AlterField(
            model_name='datastatistik',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_statistik', to='statistik.kategoristatistik'),
        ),
        migrations.RemoveField(
            model_name='datastatistik',
            name='kategori_baru',
        ),
    ]
