# Generated by Django 5.2.7 on 2025-11-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='foto_produk',
        ),
        migrations.AddField(
            model_name='umkm',
            name='foto_utama',
            field=models.ImageField(blank=True, help_text='Foto terbaik yang mewakili usaha Anda', null=True, upload_to='umkm_utama/'),
        ),
        migrations.AddField(
            model_name='umkm',
            name='kontak_instagram',
            field=models.CharField(blank=True, help_text='Nama pengguna Instagram, cth: @desa.wayhalim', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='kontak_telepon',
            field=models.CharField(blank=True, help_text='Nomor WhatsApp atau Telepon', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='link_ecommerce',
            field=models.URLField(blank=True, help_text='Link ke Tokopedia, Shopee, dll.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='lokasi',
            field=models.CharField(blank=True, help_text='Contoh: Jl. Mawar No. 10', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='deskripsi',
            field=models.TextField(help_text='Deskripsi umum tentang toko/usaha Anda'),
        ),
        migrations.CreateModel(
            name='FotoUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='umkm_gallery/')),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_gallery', to='umkm.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200)),
                ('deskripsi_produk', models.TextField(blank=True, null=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk_list', to='umkm.umkm')),
            ],
        ),
    ]
