# Generated by Django 5.2.7 on 2025-10-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=200)),
                ('nama_pemilik', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('foto_produk', models.ImageField(upload_to='foto_umkm/')),
                ('status', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu Persetujuan', max_length=30)),
            ],
        ),
    ]
