# Generated by Django 5.2.7 on 2025-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_umkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='galeri/')),
            ],
        ),
        migrations.CreateModel(
            name='LingkunganRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lingkungan', models.CharField(max_length=100)),
                ('nomor_rt', models.CharField(max_length=5)),
                ('nama_ketua_rt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='struktur_organisasi/')),
            ],
        ),
    ]
