# Generated by Django 5.2.7 on 2025-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_galeri_lingkunganrt_strukturorganisasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='strukturorganisasi',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
