# Generated by Django 5.2.7 on 2025-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_strukturorganisasi_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(upload_to='berita_pics/')),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_publikasi'],
            },
        ),
    ]
