# Generated by Django 5.2.7 on 2025-11-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_berita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Berita',
        ),
    ]
