# Generated by Django 5.2.7 on 2025-11-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_delete_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Tempelkan kode SVG ikon di sini', null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Layanan',
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=200)),
                ('deskripsi_lengkap', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan_list', to='profil.kategorilayanan')),
            ],
            options={
                'verbose_name_plural': 'Layanan',
            },
        ),
    ]
